description = "May a Censorship Researcher."
mainSections = ["posts"]
rssFullContent = true

[Sidebar]
subtitle = "Maybe a Censorship Researcher."
emoji = "ğŸ‘€"

[colorScheme]
toggle = true
default = "auto"

[Sidebar.avatar]
enabled = true
local = true
src = "avatar.jpg"

[Footer]
since = 2024
customText = """
ä¸è‡ªç”±æ‹¥æŠ±ã€‚Embrace Liberty.<br />
<a href="https://icp.gov.moe/?keyword=20242952" target="_blank" rel="noopener">
    <b>èŒICPå¤‡20242952å·</b>
</a><text> | 
æœ¬ç«™æ€»è®¿é—®é‡ <b>NaN</b> æ¬¡
</text>
<br />
æ”¯æŒ
<a href="https://ready.chair6.net/?url=https%3A%2F%2Fobjshadow.pages.dev" target="_blank" rel="noopener">
    <b>IPv6</b>
</a>, 
<a href="https://http3check.net/?host=objshadow.pages.dev" target="_blank" rel="noopener">
    <b>HTTP/3</b>
</a>, 
<a href="https://datatracker.ietf.org/doc/html/rfc8446" target="_blank" rel="noopener">
    <b>TLS 1.3</b>
</a> åŠ
<a href="https://hstspreload.org/?domain=objshadow.pages.dev" target="_blank" rel="noopener">
    <b>HSTS Preload</b>
</a> &amp; 
<a href="https://www.cloudflare.com/dns/dnssec/how-dnssec-works/" target="_blank" rel="noopener">
    <b>DNSSEC</b>
</a>
"""

[Article]
toc = true
wordCount = true
viewsCount = true
readingTime = true
license.enabled = true
license.default = "Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[DateFormat]
published = "2006-01-02 PM"
lastUpdated = "2006-01-02 PM"

[Comments]
enabled = true
provider = "giscus"

[Comments.Giscus]
repo = "ShadowObj/blog"
repoID = "R_kgDOMcbEhw"
category = "Announcements"
categoryID = "DIC_kwDOMcbEh84ChRoq"
mapping = "pathname"
reactionsEnabled = 1
emitMetadata = 0

[widgets]
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"
[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"
[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"
[widgets.homepage.params]
limit = 15

[[widgets.homepage]]
type = "milestone"

[[widgets.page]]
type = "toc"
